application: nickmichaelsfinegallery
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /static/(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

# image files
- url: /static/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))


# Page Handlers

- url: /admin.*
  script: routes.admin.app
  login: admin

- url: /.*
  script: routes.public.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest